# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: set the release version (tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: "Install Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: "Install TinyGo"
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.35.0/tinygo_0.35.0_amd64.deb
          sudo dpkg -i tinygo_0.35.0_amd64.deb

      - name: Make
        env:
          ENABLE_WASM_OPT: false
        run: make build

      - name: generate checksums
        run: |
          sha256sum redirect.wasm > checksums-${{ env.RELEASE_VERSION }}.txt

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            redirect.wasm
            checksums-${{ env.RELEASE_VERSION }}.txt
